---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: Doc es el asistente de IA de NetApp disponible en docs.NetApp.com. Responde a preguntas utilizando solo el contenido de este sitio. Doc no usa contenido de otros sitios de NetApp o Internet público para responder preguntas. 
---
= Descripción general del asistente generativo con tecnología de IA de NetApp
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Doc es el asistente de IA de NetApp disponible en docs.NetApp.com. Responde a preguntas utilizando solo el contenido de este sitio. Doc no usa contenido de otros sitios de NetApp o Internet público para responder preguntas.

Doc puede crear respuestas a partir de preguntas anteriores, sugerir preguntas adicionales y explicar cómo genera respuestas. Esto lo convierte en una herramienta valiosa para navegar por la documentación de NetApp.



== Ámbito y limitaciones

Doc solo puede responder preguntas basadas en contenido seleccionado publicado en docs.NetApp.com.


NOTE: Durante esta fase beta, Doc no está entrenado en todo el contenido docs.NetApp.com. Los documentos pueden responder a preguntas sobre contenido como, entre otros, contenido de ONTAP, BlueXP , StorageGRID, Keystone y SnapCenter. Si necesita información que Doc no tiene, háganoslo saber.

* Doc responde a las preguntas basándose únicamente en la última versión publicada de un producto. Por ejemplo, si existe documentación para las versiones 1.0 y 2.0 de un producto, Doc solo consulta la documentación 2.0 más reciente.
* Para obtener mejores resultados, sea siempre específico con los nombres de los productos. Doc sabe en qué página se encuentra cuando hace una pregunta, pero es solo uno de los varios factores que Doc tiene en cuenta al formular una respuesta.
* Doc puede chatear en los idiomas compatibles con docs.NetApp.com, pero no está entrenado para versiones que no sean en inglés.




== Escribir buenos mensajes

Sigue estos consejos para la mejor experiencia con Doc.

Haga preguntas específicas.:: Escriba preguntas detalladas y especifique el nombre del producto, la versión y el tipo de interfaz (GUI, API). Por ejemplo:
+
--
[]
====
¿Qué pasos debo seguir en System Manager para actualizar de ONTAP 9,8 a ONTAP 9.12.1?

====
--
Pida los pasos necesarios para completar una tarea.:: Pida a Doc que incluya los pasos para completar un proceso. En lugar de preguntar _Cómo instalo el conector BlueXP  sin internet?_ Prueba:
+
--
[]
====
¿Qué pasos debo seguir para instalar el conector BlueXP  sin Internet?

====
--
Divide las preguntas complejas en fragmentos.:: Divida las preguntas complejas en preguntas más pequeñas (también conocidas como _chaining_). Doc recuerda las preguntas anteriores y crea respuestas más complejas a medida que continúa charlando.
+
--
Por ejemplo, en lugar de preguntar a Doc _How do to configure ransomware protection and backup schedules in BlueXP ?_ try:

[]
====
¿Cuáles son los pasos para configurar la protección frente al ransomware en BlueXP ?

====
a continuación, pregunte:

[]
====
¿Cuáles son los pasos para configurar programaciones de backup en BlueXP ?

====
--
Use comillas.:: Las frases de varias palabras deben escribirse entre comillas. Esto ayuda a Doc a reconocer la frase como un concepto único, de forma similar a cómo podrías enfatizarla en una conversación con un ser humano.
+
--
Por ejemplo, en esta pregunta, «¿cómo se calcula la eficiencia del almacenamiento en ONTAP?_ Doc podría pensar que está preguntando _storage_ y _efficiency_ como dos palabras no relacionadas. En su lugar, pruebe:

[]
====
¿Cómo se calcula la «eficiencia del almacenamiento» en ONTAP?

====
--
Revise cómo respondió Doc.:: Después de responder, Doc proporciona información sobre cómo generó su respuesta. Esto puede darte ideas sobre cómo refinar tu pregunta para obtener los resultados que deseas.
Borre su historial de chat:: Si desea cambiar los temas, borre el chat de inicio de nuevo. Dado que Doc recuerda preguntas anteriores, los cambios en el tema pueden producir resultados inesperados.




== Comentarios

Sus comentarios nos ayudan a mejorar la forma en que responde Doc. Utilice la herramienta de comentarios en la ventana de chat Doc para informarnos si las respuestas son precisas y útiles o si necesitan mejorar. También puede enviar por correo:ng-doccomments@NetApp.com[contacto con nosotros] con preguntas o comentarios.
