---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: Doc es nuestro asistente generativo impulsado por IA en docs.netapp.com. Doc está diseñado para responder a preguntas sobre productos de NetApp utilizando contenido publicado en docs.NetApp.com. 
---
= Descripción general del asistente generativo con tecnología de IA de NetApp
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Doc es nuestro asistente generativo impulsado por IA en docs.netapp.com. Doc está diseñado para responder a preguntas sobre productos de NetApp utilizando contenido publicado en docs.NetApp.com.

Doc puede crear respuestas a partir de preguntas anteriores, sugerir preguntas adicionales y explicar cómo genera respuestas. Esto lo convierte en una herramienta valiosa para navegar por la documentación de NetApp.



== Ámbito y limitaciones

Doc solo puede responder preguntas basadas en contenido seleccionado publicado en docs.NetApp.com.


NOTE: Durante la fase Beta, Doc utiliza la mayor parte, pero no todo, del contenido publicado en docs.netapp.com para responder preguntas. Doc está familiarizado con toda la documentación de ONTAP, BlueXP, StorageGRID, E-Series, Keystone y SnapCenter y la utiliza para responder preguntas sobre estos productos. Por otro lado, no está familiarizado con la documentación de algunos productos heredados. Por ejemplo, no utiliza la documentación de SnapDrive for UNIX para proporcionar respuestas. Durante la Beta, estamos trabajando para perfeccionar los conocimientos de Doc. Si necesita información que Doc no tenga, envíenos un correo electrónico a: ng-doccomments@netapp.com [infórmenos].

* Doc responde a las preguntas basándose únicamente en la última versión publicada de un producto. Por ejemplo, si existe documentación para las versiones 1.0 y 2.0 de un producto, Doc solo consulta la documentación 2.0 más reciente.
* Para obtener mejores resultados, sea siempre específico con los nombres de los productos. Doc sabe en qué página se encuentra cuando hace una pregunta, pero es solo uno de los varios factores que Doc tiene en cuenta al formular una respuesta.
* Doc puede chatear en los idiomas compatibles con docs.NetApp.com, pero no está entrenado para versiones que no sean en inglés.




== Escribir buenos mensajes

Sigue estos consejos para la mejor experiencia con Doc.

Haga preguntas específicas.:: Escriba preguntas detalladas y especifique el nombre del producto, la versión y el tipo de interfaz (GUI, API). Por ejemplo:
+
--
[]
====
¿Qué pasos debo seguir en System Manager para actualizar de ONTAP 9,8 a ONTAP 9.12.1?

====
--
Pida los pasos necesarios para completar una tarea.:: Pida a Doc que incluya los pasos para completar un proceso. En lugar de preguntar _Cómo instalo el conector BlueXP  sin internet?_ Prueba:
+
--
[]
====
¿Qué pasos debo seguir para instalar el conector BlueXP  sin Internet?

====
--
Divide las preguntas complejas en fragmentos.:: Divida las preguntas complejas en preguntas más pequeñas (también conocidas como _chaining_). Doc recuerda las preguntas anteriores y crea respuestas más complejas a medida que continúa charlando.
+
--
Por ejemplo, en lugar de preguntar a Doc _How do to configure ransomware protection and backup schedules in BlueXP ?_ try:

[]
====
¿Cuáles son los pasos para configurar la protección frente al ransomware en BlueXP ?

====
a continuación, pregunte:

[]
====
¿Cuáles son los pasos para configurar programaciones de backup en BlueXP ?

====
--
Use comillas.:: Las frases de varias palabras deben escribirse entre comillas. Esto ayuda a Doc a reconocer la frase como un concepto único, de forma similar a cómo podrías enfatizarla en una conversación con un ser humano.
+
--
Por ejemplo, en esta pregunta, «¿cómo se calcula la eficiencia del almacenamiento en ONTAP?_ Doc podría pensar que está preguntando _storage_ y _efficiency_ como dos palabras no relacionadas. En su lugar, pruebe:

[]
====
¿Cómo se calcula la «eficiencia del almacenamiento» en ONTAP?

====
--
Revise cómo respondió Doc.:: Después de responder, Doc proporciona información sobre cómo generó su respuesta. Esto puede darte ideas sobre cómo refinar tu pregunta para obtener los resultados que deseas.
Borre su historial de chat:: Si quieres cambiar de tema (por ejemplo, si quieres preguntar sobre un producto diferente), borra el historial del chat para iniciar una nueva sesión. Si no borras el historial del chat antes de iniciar un nuevo tema, podrías obtener resultados inexactos.




== Comentarios

Estamos trabajando para mejorar continuamente Doc. Envíenos sus comentarios dentro de la ventana de chat de Doc. Háganos saber si las respuestas de Doc son precisas y útiles o si están incompletas o de alguna manera insuficientes. También puede enviar por correo:ng-doccomments@NetApp.com[contacte con nosotros] si tiene alguna pregunta o inquietud con respecto a las capacidades o respuestas del documento.
