---
settings:
  name: About docs.netapp.com
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Acerca de los sitios
    url: "/docs-netapp-com.html"
  - title: About Doc (asistente con tecnología de IA)
    url: "/doc-gen-ai-assistant.html"
  - title: Avisos legales
    url: "/legal-notices.html"
